extends:
  - eslint:recommended
  - plugin:flowtype/recommended

parser: babel-eslint

plugins:
  - flowtype

globals:
  Promise: false

env:
  node: true

rules:
  no-console: [2, allow: [warn, error]]
  no-extra-semi: 0
